
drill<-function(x,row,col) {
  l<-length(x)
  results<-vector()
  for(i in c(1:l)) {
    results<-append(results,x[[i]][row,col])
  }
  return(results)
}

#' Calculate significance statistics
#'
#' Calculate significance statistics based on a list returned
#' by \code{\link{randomGraphs}}
#'
#' @param x a n x n association matrix returned by \code{\link{makeAssociation}}
#' @param rgraphs a list object returned by \code{\link{randomGraphs}}
#'
#' @return A list of significance statistics:
#'    \item{pl}{A n x n matrix containing the percentage for each cell
#'      of random association graphs that have values below the value in \code{x}.
#'      This is essentially a p-value for whether \code{x_ij} is lower than expected}
#'    \item{pu}{A n x n matrix containing the percentage for each cell
#'      of random association graphs that have values above the value in \code{x}.
#'      This is essentially a p-value for whether \code{x_ij} is higher than expected}
#'    \item{S}{The mean square deviation of the association matrix \code{x}}
#'    \item{Sp}{The percentage of random association matrices with mean square deviations
#'      greater than \code{S}. This is essentially a p-value for whether the mean square
#'      deviation of \code{S} is significantly larger than random, and thus that associations
#'      overall are occuring significantly more often than random.}


getSig<-function(x,rgraphs) {
  nr<-dim(x)[1]
  nc<-dim(x)[2]
  pu<-matrix(nrow=nr,ncol=nc)
  pl<-matrix(nrow=nr,ncol=nc)
  numgraphs<-length(rgraphs$a)
  for( i in c(1:nr) ) {
    for(j in c(1:nc) ) {
      t<-x[i,j]
      g<-rgraphs$a[drill(rgraphs$a,i,j)>=t]
      puc<-length(g)/numgraphs
      g<-rgraphs$a[drill(rgraphs$a,i,j)<=t]
      plc<-length(g)/numgraphs
      pu[i,j]<-puc
      pl[i,j]<-plc
    }
  }
  std<-apply(simplify2array(rgraphs$a),c(1,2),sd)
  S<-msdAssoc(x,e=rgraphs$expected)
  ses<-sapply(rgraphs$a,msdAssoc,e=rgraphs$expected)
  Sp<-length(ses[which(ses>S)])/length(rgraphs$a)
  results<-list(pl=pl,pu=pu,sd=std,S=S,Sp=Sp)
  return(results)
}

#' Calculate the mean square deviation of an association matrix
#'
#' This calculates the mean square deviation of an association
#' matrix returned by \code{\link{makeAssociation}}. Used internally by
#' \code{\link{getSig}}.
#'
#' @param g an association matrix generated by \code{\link{makeAssociation}}
#' @param e the expected association matrix returned by \code{\link{randomGraphs}}
#'  (The \code{expected} object in the returned list)
#'
#' @return A numeric value equal to the mean square deviation of \code{g}

msdAssoc<-function(g,e) {
  g[is.nan(g)]<-0
  o<-g-e
  o<-o^2
  s<-sum(o)
  D<-dim(g)[1]
  D<-D^2
  S<-s/D
  return(S)
}

#need to break x out into a and ra
test.assoc<-function(x,FUN=net.density,...) {
  xvalue<-FUN(x$assoc,...)
  xrand<-sapply(x$random$a,FUN=FUN,...)
  pscore.up<-length(which(xrand>=xvalue))/length(xrand)
  pscore.down<-length(which(xrand<=xvalue))/length(xrand)
  mean.xrand<-mean(xrand)
  sd.xrand<-sd(xrand)
  return(list(value=xvalue,random.value=mean.xrand,sd.value=sd.xrand,p.up=pscore.up,p.down=pscore.down))
}

#need to break x and y out into a and ra
test.assoc.diff<-function(x,y,FUN=net.density,...) {
  xvalue<-FUN(x$assoc,...)
  yvalue<-FUN(y$assoc,...)
  xrand<-sapply(x$random$a,FUN=FUN,...)
  yrand<-sapply(y$random$a,FUN=FUN,...)
  diff<-xvalue-yvalue
  diff.rand<-xrand-yrand
  pscore.up<-length(which(diff.rand>=diff))/length(diff.rand)
  pscore.down<-length(which(diff.rand<=diff))/length(diff.rand)
  mean.diff.rand<-mean(diff.rand)
  sd.diff.rand<-sd(diff.rand)
  return(list(diff=diff,random.diff=mean.diff.rand,random.sd=sd.diff.rand,p.up=pscore.up,p.down=pscore.down))
}
